<!DOCTYPE HTML>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta name="description" content="ミツエーリンクスのコラム「{{TITLE}}}」です。">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{TITLE}}} | コラム | ミツエーリンクス</title>
<link rel="stylesheet" href="/cmn/css/basic.css" media="screen,print">
<link rel="stylesheet" href="/cmn/css/print.css" media="print">
</head>
<body itemscope itemtype="http://schema.org/WebPage" class="knowledge">

<header>
<div class="header_content" itemscope itemtype="http://schema.org/Corporation">
<a href="/" id="logo" itemprop="url"><img src="/cmn/img/logo.png" alt="ミツエーリンクス" itemprop="logo"></a>
<div class="management_ideology">Smart Communication Design Company</div>
<form method="get" action="/search/index.php"><label for="site_search">サイト内検索</label><input type="text" maxlength="100" name="keyword" id="site_search"><button type="submit" id="btn_site_search"><img src="/cmn/img/btn_search.png" alt="検索"></button><input type="hidden" name="start" value="1"></form>
<nav>
<ul class="utility">
<li class="home"><a href="/">ホーム</a></li><li class="sitemap"><a href="/sitemap/">サイトマップ</a></li><li class="contact"><a href="/contact/">お問い合わせ</a></li><li class="lang"><a href="/english/" lang="en" hreflang="en">English</a></li>
</ul>
<ul class="global_nav" itemscope="itemscope" itemtype="http://www.schema.org/SiteNavigationElement">
<li itemprop="name" class="service"><a itemprop="url" href="/service/">サービス</a></li>
<li itemprop="name" class="our_work"><a itemprop="url" href="/our_work/">実績紹介</a></li>
<li itemprop="name" class="knowledge"><em aria-current="true"><a itemprop="url" href="/knowledge/">ナレッジ</a></em></li>
<li itemprop="name" class="seminar"><a itemprop="url" href="/seminar/">セミナー</a></li>
<li itemprop="name" class="news"><a itemprop="url" href="/news/">ニュース</a></li>
<li itemprop="name" class="company"><a itemprop="url" href="/company/">会社情報</a></li>
<li itemprop="name" class="careers"><a itemprop="url" href="/careers/">採用情報</a></li>
</ul>
</nav>
</div>
</header>

<main id="content">
<div itemprop="breadcrumb" class="topic_path"><a href="/"><img src="/cmn/img/icon_home.gif" alt="ホーム"></a> &gt; <a href="/knowledge/">ナレッジ</a> &gt; <a href="/knowledge/column/">コラム</a> &gt; <a href="/knowledge/column/2019.html">2019年</a> &gt; <em aria-current="page"><?= $title ?></em></div>
<div id="main_content">

<h1 class="hdg_l1_1"><?= $title ?></h1>

<div class="column_meta_2">
<div class="date"><?= date('Y年m月d日', strtotime($date)) ?></div>
<div class="writer"><?= $position ?><br><?= $user ?></div>
</div>

<?= $body ?>

<div class="nav_archive_1">
<ul>
<li class="prev"><a href="<?= $prev['id'] ?>.html"><span class="mark">前の記事へ</span><?= $prev['title'] ?></a></li>
<li class="next"><a href="<?= $next['id'] ?>.html"><span class="mark">次の記事へ</span><?= $next['title'] ?></a></li>
</ul>
</div>

<div class="nav_back_1"><a href="/knowledge/column/2019.html"><span class="text">2019年のコラム一覧に戻る</span></a></div>

<div class="nav_contact_1 mailnews">
<p>メールニュースでは、本サイトの更新情報や業界動向などをお伝えしています。ぜひご購読ください。</p>
<div class="button"><a href="/form/index.php?id=M2">メールニュース登録</a></div>
</div>

<!-- /#main_content --></div>
<div id="local_nav">
<nav>
<ul class="adjacent_items">
<li><a href="/knowledge/column/">コラム</a></li>
<li><a href="/knowledge/blog/">Blog</a></li>
<li><a href="/knowledge/colors/">広報誌「MITSUE COLORS」</a></li>
<li><a href="https://www.mitsue.co.jp/form/index.php?id=M2">メールニュース</a></li>
<li><a href="/knowledge/social_media_accounts.html">ソーシャルメディア 公式アカウント</a></li>
<li><a href="/knowledge/marketing/">Webマーケティング資料集</a></li>
<li><a href="/knowledge/glossary.html">用語集</a></li>
</ul>
</nav>
</div>
<!-- /#content --></main>

<footer>
<div class="footer_content">
<dl>
<dt>信頼を支えるマネジメントシステム</dt>
<dd><ul><li><img src="/cmn/img/iso.png" alt="品質マネジメントシステム ANAB BSI FS559479/ISO9001 情報セキュリティマネジメントシステム ANAB BSI ISMS IS60384/ISO27001（認証取得事業所：本社およびスタジオ）"></li><li><a href="https://privacymark.jp/" class="privacy"><img src="/cmn/img/p_mark.png" alt="プライバシーマーク 10820129(09)"></a></li></ul></dd>
</dl>
<ul class="banner">
<li><a href="https://videocenter.mitsue.co.jp/" class="videocenter"><img src="/cmn/img/banner_videocenter.gif" alt="ミツエーリンクスの動画ポータルサイト Video Center"></a></li>
<li><a href="https://www.w3.org/Consortium/Member/Testimonial/Home/home-899" class="w3c"><img src="/cmn/img/w3c.png" alt="ミツエーリンクスはW3Cの会員です。"></a></li>
</ul>
<ul class="utility">
<li class="privacy_policy"><a href="/privacy_policy.html">プライバシーポリシー</a></li>
<li class="site_policy"><a href="/site_policy.html">サイトポリシー</a></li>
<li class="help"><a href="/help/">ヘルプ</a></li>
<li class="contact"><a href="/contact/">お問い合わせ</a></li>
</ul>
<small class="copyright">&copy; Mitsue-Links Co.,Ltd.</small>
</div>
</footer>

<script src="/cmn/js/mjl.js"></script>
<script src="/cmn/js/run.js"></script>
<!-- Google Tag Manager -->
<!-- End Google Tag Manager -->

</body>
</html>
